### ISSUE TITLE
simple workflow: list available updates, update selectively, don't crash, don't background

### ISSUE THREAD

**Issue by mralusw** [wimpysworld/deb-get#1011]
How can I achieve the simple workflow of
```
apt update
apt list --upgradable
apt install  # some but not all
```

... especially since `deb-get` crashes in the update step if one of the packages is broken (some nonsense about unset variables, I'm sure you see it all the time, with `croc`, `tonelib-noise-creator`, `fastfetch` and whatnot)

... and also since `update` "optimizes" usage by backgrounding itself, but then printing random lines (some mis-aligned) on the terminal.

**Comment by philclifford** [comment]
`--quiet` will remove the non-random output from `curl` which appears to have issues with alignment (apparently fixed in more recent versions of `curl`)
 
for the broken package definitions you need to grab the fixed definitions from the pending PRs (either manually drop them in `/etc/deb-get/99-local.d/`  or add an external repo which supplies them as I outlined here https://github.com/wimpysworld/deb-get/issues/1008#issuecomment-1943817070

You could also get a version of `deb-get` with more resilience to upstream packaging or presentation changes ( e.g. check out #999 ).

If a number of packages have update available you can selectively update those you wish to b ut not all with

```
deb-get update --quiet
deb-get install foo bar # but not baz
```

**Comment by philclifford** [comment]
Now that #1027 has been submitted and merged 999 is no longer relevant
