### ISSUE TITLE
New version for Ubuntu 24.04

### ISSUE THREAD

**Issue by teejee2008** [wimpysworld/deb-get#1081]
Please release a new version with the latest changes. Anyone trying to install the DEB file from the current release, or by running the installation command mentioned in README will get an error on Noble.

**Comment by Xmetalfanx** [comment]
was looking to see if someone else asked this.   looking through the commit history ... there HAS been work done already on it.

- https://github.com/wimpysworld/deb-get/commit/594dbb0bc0b6bcee7cbe58a82042e032182d0377
- https://github.com/wimpysworld/deb-get/commit/9f3ce5cadce6f0d3b44229de6eb256ef16c19252
- https://github.com/wimpysworld/deb-get/commit/a9f9b546cc26cb03d11c03741684d6fdc3c81d90
- https://github.com/Xmetalfanx/linuxSetup/commit/64ca338f42d6d2c6f357bef0375fc75515c27d83

**Comment by teejee2008** [comment]
Yes the current version of deb-get in the repo fully supports Ubuntu 24.04. There is no change required to the code. All that is needed is to package a new release, so that people can install it. As it stands currently, users need to clone the repo and install it manually, instead of just downloading the DEB from release page. Running the command mentioned in README also doesn't work since it downloads the version from the Release page.

**Comment by teejee2008** [comment]
Here's a simple bash script to install it from the repo in case someone needs it.
[install_deb-get_current.txt](https://github.com/wimpysworld/deb-get/files/15384522/install_deb-get_current.txt)

**Comment by elreydetoda** [comment]
As a temporary workaround, I did the following (till they officially do a new release):
```console
# download repo
$ git clone https://github.com/wimpysworld/deb-get.git

# start up a container to follow their publishing step (while in root of repo)
$ podman container run --rm -it -v "${PWD}":/app -w /app docker.io/ubuntu:24.04
```

Then follow their [build & release workflow](https://github.com/wimpysworld/deb-get/blob/ce5f0c233a7e8124c6b559fc20df6df6a7086244/.github/workflows/publish-release.yml#L29-L33) but change the [dch command](https://github.com/wimpysworld/deb-get/blob/ce5f0c233a7e8124c6b559fc20df6df6a7086244/.github/workflows/publish-release.yml#L32) to be something like `-999` instead of `-1` (since I don't think they'll use that): `dch -v "${REL_VER}-999" --distribution=unstable "New upstream release."`.

Then I could install it on my machine, current commit is: ce5f0c233a7e8124c6b559fc20df6df6a7086244

**Comment by siriak** [comment]
Is there an ETA for the next release? I tried the script shared by @teejee2008, but it didn't work for me for some reason. I don't feel like troubleshooting it, so I'll just wait for a new version to be released.

**Comment by felicianotech** [comment]
Tagging people who should have write access: @flexiondotorg @philclifford 

We would appreciate your help gents.

**Comment by flexiondotorg** [comment]
Fixed via https://github.com/wimpysworld/deb-get/releases/tag/0.4.1

**Comment by felicianotech** [comment]
Thank you
