### ISSUE TITLE
Re-add Picocrypt

### ISSUE THREAD

**Issue by sbstn87** [wimpysworld/deb-get#1114]
- [X] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Picocrypt
 - Download URL: https://github.com/Picocrypt/Picocrypt/releases
 - Website URL: https://github.com/Picocrypt/Picocrypt
 - App Summary: Picocrypt is a very small (hence Pico), very simple, yet very secure encryption tool that you can use to protect your files. It's designed to be the go-to tool for encryption, with a focus on security, simplicity, and reliability. Picocrypt uses the secure XChaCha20 cipher and the Argon2id key derivation function to provide a high level of security, even from three-letter agencies like the NSA.

Picocrypt has been previously available via deb-get (https://github.com/wimpysworld/deb-get/issues/167), but it stopped publishing .deb packages. Now, they are available again:

https://github.com/Picocrypt/Picocrypt/issues/10

**Comment by sbstn87** [comment]
By the way, it is one of the recommended encryption tool on the Privacy Tools website:

https://www.privacytools.io/secure-file-encryption

**Comment by HACKERALERT** [comment]
Awesome, thanks.

**Comment by philclifford** [comment]
Please check https://github.com/wimpysworld/deb-get/blob/main/01-main/CONTRIBUTING.md#adding-software - in particular : 

  * **Only stable/production releases**. Daily/nightly, betas or pre-release versions will not be accepted.
  * GitHub Releases and direct downloads **must have a reliable means to dynamically determine the current upstream published version**. Hardcoded versions will be not accepted.


The second is critical: we must be able to determine the version available to compare with any installed package. Typically we do this for github releases by using the api to get the "latest" release and extract the version tag.

It is likely that nightly automated releases will not be acceptable in any case (yes there are "exceptions"  - which may at any time be tidied up of course).  I'd recommend tweaking the automated workflows to make periodic intentional stable release versions labelled "latest" and label the nightlies as "nightly".  Otherwise if declined there is always the option of an external deb-get repository supporting the nightly release, but being included in the core repo would of course be best all round.

I note also in the discussion linked above that there are indications that debian < 12 and derivatives may now be unsupported (the deb compression support). Ideally the more widely acceptable compression option has been adopted, but if not we would need to specify supported releases in the definition, so confirmation either way would be helpful.

I have a "working" definition (https://github.com/philclifford/deb-get/blob/extras/81-betas/packages/picocrypt-gui ) almost ready for a PR once the app version is not hard-coded to 1 and tagged in the release.

**Comment by HACKERALERT** [comment]
Thanks for the info. I'll make a latest tag some time today or tomorrow that only releases manually.

As for the Debian version, I fixed it. Debian 11 and Ubuntu 22 should be supported.

**Comment by philclifford** [comment]
@HACKERALERT Thanks!

**Comment by HACKERALERT** [comment]
@philclifford Stable tagged releases out now!

https://github.com/Picocrypt/Picocrypt/releases

Let me know if this is sufficient.

**Comment by HACKERALERT** [comment]
Oops, missed that. I'll fix that in a few days (busy atm). Thanks for pointing it out.

**Comment by HACKERALERT** [comment]
@philclifford had a minute today, fixed. Can you try again?

**Comment by philclifford** [comment]
@HACKERALERT That's fine, thanks.  PR now awaiting review.

**Comment by HACKERALERT** [comment]
Thanks!
