### ISSUE TITLE
Request: Yazi

### ISSUE THREAD

**Issue by Rabalder9** [wimpysworld/deb-get#1158]
## Requesting a new app ✨

 - [x] I have checked that this app does not already have a pending request and has not previously been declined.
 - App Name: Yazi
 - Download URL: https://github.com/sxyazi/yazi/releases
 - Website URL: https://yazi-rs.github.io/
 - App Summary: It's a terminal file manager like ranger, just much faster and snappier.

**Comment by philclifford** [comment]
Alas no deb packaging available. Until there is this will have to be left to `nix`, `snap` or `rustup` I guess.

**Comment by philclifford** [comment]
The nightly builds now have deb assets so hopefully we can be ready for the next release.
Some things to bear in mind: 

-  ~this depends on `fd-find` which will replace `fd` so Jammy users of `fd` from github via `deb-get` will get a downgrade and find `fd` removed by `apt` - potential for a new bit of dependency hell with a tweak (maybe `deb-get` will be left with `fd` in the installed list ....)~ Fixed upstream
-  Any PR should remain draft until a release of `yazi` with deb assets is made
-  there are `musl` and `gnu` debs so that needs handling (i.e. pick one - users will need to override if they want the other I think)

**Comment by Xmetalfanx** [comment]
while there is no DEB for the stable install, i just saw (not sure if they always do this) a DEB for the nightly build listed on the release page so MAYBE they could be adding one.

Unrelated to deb-get, I already knew about yazi before seeing this issue, and installed it via Homebrew (which i doesn't have a deb either ... just a script that installs it)
