### ISSUE TITLE
`deb-get --help` does not work

### ISSUE THREAD

**Issue by Ahmed-E-86** [wimpysworld/deb-get#340]
## Requesting a new feature 🧑‍💻

`deb-get --help` & `deb-get -h` does nothing.

Adding the command-line arguments --help & -h would be useful for the new users of this application.

**Comment by peutch** [comment]
Hi,
But have you tried just: `deb-get help`? (not an option but a command)

**Comment by Ahmed-E-86** [comment]
I know that `deb-get help` exists, but can you figure that out without looking in the documentation of the git repo?

**Comment by peutch** [comment]
I am just a deb-get user and trying to help.
For me this is often another (blind) alternative when a command does not give its usage without any arguments or using --help or -h.

More over my system is a Debian Sid, so:
1. the provided .deb package is not installable (because based on the zstd compression) without repacking it (note that I have a script for that).
2. `deb-get` says:
` [!] ERROR! Debian Sid is not supported because it is not derived from a supported Debian or Ubuntu release.`
and its source code have to be changed to work.

**Comment by natanjunges** [comment]
@peutch please open a new issue detailing your problems so we can keep track of each issue (you can then use the provided template for reporting bugs so we have more information to help).

**Comment by peutch** [comment]
thanks @natanjunges so I opened two issues: #350  and #351.
You may also be interested by my post to the debian-user mailing list: https://lists.debian.org/debian-user/2022/07/msg00421.html

**Comment by Xmetalfanx** [comment]
> I know that `deb-get help` exists, but how can you figure that out without looking at the documentation of the git repo first?

i agree ... i tried --help force of habit in the CLI ... even if "deb-get help" stays for example .. adding --help is a good idea in my view

**Comment by flexiondotorg** [comment]
Now every terminal app adheres to `--help`. This is an intentional choice.
