### ISSUE TITLE
Bug installing rstudio

### ISSUE THREAD

**Issue by RicardoRios46** [wimpysworld/deb-get#734]
## Reporting a bug 🐛

- [x] Please make sure the version of `deb-get` you are using is up to date:

### Expected behavior

I am trying to install rstudio via deb get.

### Actual behavior

deb-get is unable to do the installation. It gave me the following message:

`[!] ERROR! Download URL for rstudio is empty. Skipping.`

### Steps to reproduce

I just tried to install the package. I have installed a lot of other packages and this is the only one that gives me that error.

`deb-get install rstudio`

### System information

Run the following a paste the output below:

#### /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

#### /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

#### deb-get version
0.3.6

### deb-get update
Ign:1 http://repo.netdata.cloud/repos/edge/ubuntu jammy/ InRelease
Hit:2 https://brave-browser-apt-release.s3.brave.com stable InRelease
Hit:3 https://dl.google.com/linux/chrome/deb stable InRelease
Hit:4 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:5 https://packages.microsoft.com/repos/vscode stable InRelease
Get:6 https://zotero.retorque.re/file/apt-package-archive ./ InRelease [2 153 B]
Ign:7 http://repo.netdata.cloud/repos/repoconfig/ubuntu jammy/ InRelease
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:9 http://mx.archive.ubuntu.com/ubuntu jammy InRelease
Hit:10 http://repo.netdata.cloud/repos/edge/ubuntu jammy/ Release
Hit:11 http://mx.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:12 http://repo.netdata.cloud/repos/repoconfig/ubuntu jammy/ Release
Hit:13 http://mx.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:14 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:17 https://ppa.launchpadcontent.net/phoerious/keepassxc/ubuntu jammy InRelease
Hit:18 https://ppa.launchpadcontent.net/sunderme/texstudio/ubuntu jammy InRelease
Fetched 2 153 B in 2s (1 107 B/s)
Reading package lists...
  [+] Updating /var/cache/deb-get/bat.json
  [+] Updating /var/cache/deb-get/bitwarden.json
  [+] Updating /var/cache/deb-get/deb-get.json
  [+] Updating /var/cache/deb-get/du-dust.json
  [+] Updating /var/cache/deb-get/duf.json
  [+] Updating /var/cache/deb-get/fd.json
  [+] Updating /var/cache/deb-get/lsd.json
  [+] Updating /var/cache/deb-get/micro.json
  [+] Updating /var/cache/deb-get/onlyoffice-desktopeditors.json
  [+] onlyoffice-desktopeditors (7.1.1-57) has an update pending. 7.2.1 is available.
  [+] Updating /var/cache/deb-get/pandoc.json
  [+] pandoc (2.19.2-1) has an update pending. 3.0.1 is available.
  [+] Updating /var/cache/deb-get/rclone.json
  [+] Updating /var/cache/deb-get/rocketchat.json

**Comment by RicardoRios46** [comment]
Hello. Thank you for checking the issue. I got this message with the show command:

```
RStudio
  Package:	rstudio
  Updater:	deb-get
  Installed:	2022.07.1+554
  Published:	
  Architecture:	amd64
  Download:	
  Website:	https://www.rstudio.com/
  Summary:	Professional software for data science teams.

```

The download URL is missing :/. Playing around with other packages all have the correct URL download link. 
BTW I manually installed the .deb from the download page. I suppose that is what the Installed line is reading.
Could be a local bug? I have access to other computers on my institution (same ubuntu version) and see the same messages.

**Comment by RicardoRios46** [comment]
Checking the code of my installed deb-get I can see that is trying to download it from the old rstudio page. 
Looks like my local deb-get is behind updates.  I'll try to see why.

**Comment by RicardoRios46** [comment]
Well, apparently the real bug is that my local deb-get is probably outdated. I am quite confused about it. `deb-get version` shows 0.3.6. Trying to update it gives a message that is updated. But I can see on my `/usr/bin/deb-get` code that  `function deb_rstudio()` has the old URL downloads.

**Comment by philclifford** [comment]
There have been some huge changes since the last release, and work is ongoing to ready a new release. Sadly your `deb-get` is correct as far as being on the latest release goes.  I hope a new release is coming soon, but all I can promise is "when it is ready". Essentially you have 3 options at the moment: 

1. wait for the next release (and install/update from the current deb - still as above for jammy as I type)
2. clone the repo (or download the current code) and run that - it isn't ready for release yet obviously so I cannot recommend it, although I do (run it and recommend it) 
3.  use the current function (in `01-main/packages/rstudio` ) as a model to take the old deb_rstudio function and copy it and update it into the custom user includes directory of the last release : `/etc/deb-get.d/` .  With this approach you could also create override functions for any other app you have installed (or want to ) that has had to be fixed since the last release (there are quite a few but should be easy to find in the closed PRs)

As this issue will be closed soon please join us in the discord for further support if you need it. (I'm happy to help directly too, and also to learn a little about DW-MRI :-) )

**Comment by RicardoRios46** [comment]
Ok! I'll go for the 3rd option in the meantime. Thank you for your time. I learn a couple of things from this hehe. See ya in discord!
